version: '3.8'
services:
    # proxy_server:
    #     restart: unless-stopped
    #     image: staticfloat/nginx-certbot
    #     ports:
    #         # - 80:80/tcp
    #         - 3000:3000/tcp
    #     environment:
    #         CERTBOT_EMAIL: admin@elfactory.co.kr
    #     volumes:
    #       - ./conf.d:/etc/nginx/user.conf.d:ro
    #       - letsencrypt:/etc/letsencrypt

    proxy_server:
        image: nginx:1.25.0-alpine
        container_name: nginx
        restart: always
        ports:
          - '80:80'
          # - '443:443'
        volumes:
          # - /etc/letsencrypt/:/etc/letsencrypt/
          - /etc/letsencrypt:/etc/letsencrypt
          - ./logs/nginx/:/var/log/nginx/
          - ./nginx/:/etc/nginx/conf.d/
        environment:
          - TZ=Asia/Seoul
        depends_on:
          - nest_api-blue
          - nest_api-green    
    nest_api-blue:
        # image: elfactory_nestjs_api:latest
        image: nest-docker:latest
        container_name: ${DOCKER_APP_NAME}-blue
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
                    # - 80:80/tcp
                    - 8443:8443/tcp    
        environment:
          - TZ=Asia/Seoul
        restart: unless-stopped
    nest_api-green:
        image: nest-docker:latest
        container_name: ${DOCKER_APP_NAME}-green
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
                    # - 80:80/tcp
                    - 9443:9443/tcp    
        environment:
          - TZ=Asia/Seoul            
        restart: unless-stopped        
volumes:
    letsencrypt: